covid/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls import url
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home_view'),
    url(r'^people_data/', include('people_data.urls')),
    url(r'^people_survey/', include('people_survey.urls')),
    url(r'^hospitals/', include('hospitals.urls')),
]

hospitals/urls.py
from django.conf.urls import url

urlpatterns = [
    # ------ CRUD Entradas ------
    # url(r'^entradas_list/$', EntradasList.as_view(), name='entradas_list'),
    # url(r'^entradas_create/$', EntradasCreate.as_view(), name='entradas_create'),
    # url(r'^entradas_update/$', EntradasUpdate.as_view(), name='entradas_update'),
    # url(r'^entradas_detail/(?P<pk>.+)/$', EntradasDetail.as_view(), name="entradas_detail"),
    # -------------------------------
]

people_data/urls.py
from django.conf.urls import url

urlpatterns = [
    # ------ CRUD Entradas ------
    # url(r'^entradas_list/$', EntradasList.as_view(), name='entradas_list'),
    # url(r'^entradas_create/$', EntradasCreate.as_view(), name='entradas_create'),
    # url(r'^entradas_update/$', EntradasUpdate.as_view(), name='entradas_update'),
    # url(r'^entradas_detail/(?P<pk>.+)/$', EntradasDetail.as_view(), name="entradas_detail"),
    # -------------------------------
]

people_survey/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^survey/$', SurveyTemplateView.as_view(), name='survey'),
    url(r'^survey_result/$', SurveyResultTemplateView.as_view(), name='survey_result'),
    # ------ CRUD Entradas ------
    # url(r'^entradas_list/$', EntradasList.as_view(), name='entradas_list'),
    # url(r'^entradas_create/$', EntradasCreate.as_view(), name='entradas_create'),
    # url(r'^entradas_update/$', EntradasUpdate.as_view(), name='entradas_update'),
    # url(r'^entradas_detail/(?P<pk>.+)/$', EntradasDetail.as_view(), name="entradas_detail"),
    # -------------------------------
]

hospitals/models.py
from django.db import models

# Create your models here.

people_data/models.py
from django.db import models

# Create your models here.

people_survey/models.py
from django.db import models
from covid.model_layout import AuditFields


class SurveyedPerson(AuditFields):
    name = models.CharField(max_length=1000)
    identity_number = models.CharField(max_length=300)

    class Meta:
        managed = True
        ordering = ['identity_number']


class GeolocationPerson(AuditFields):
    POSSIBLE_RESULTS = [
        (1, 'How good!, please take this survey again in one week.'),
        (2, 'Please isolate yourself for prevention and take the survey again in three days.'),
        (3, 'Please isolate yourself for prevention and take the survey again in three days.'),
        (4, 'You have symptoms of covid19, please contact with a hospital as soon as possible.')
    ]
    surveyed_person = models.ForeignKey(SurveyedPerson, on_delete=models.CASCADE)
    survey_number = models.IntegerField()
    latitude = models.DecimalField(max_digits=15, decimal_places=8)
    longitude = models.DecimalField(max_digits=15, decimal_places=8)
    result = models.IntegerField(choices=POSSIBLE_RESULTS)

    class Meta:
        managed = True
        ordering = ['survey_number']


class SurveyAnswer(AuditFields):
    geolocation_person = models.ForeignKey(GeolocationPerson, on_delete=models.CASCADE)
    question_number = models.IntegerField()
    answer = models.IntegerField()

    class Meta:
        managed = True
        ordering = ['id']

covid/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "index.html"

hospitals/views.py
from django.shortcuts import render

# Create your views here.

people_data/views.py
from django.shortcuts import render

# Create your views here.

people_survey/views.py
from django.views.generic import TemplateView
from decimal import Decimal
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *


def save_responses(model_name, list_answers, question_number, geolocation_person):
    model_name = SurveyAnswer(geolocation_person=geolocation_person)
    model_name.question_number = question_number
    for answer in list_answers:
        model_name.answer = int(answer)
        model_name.save()
        model_name.id = None
    pass


def valid_result_from_fr(fr, ss, sm, sl):
    if 0 < fr <= 0.6:
        if 0 < ss or sm <= 0.5:
            return 2
        else:
            return 2
    elif fr == 0 and sm >= 0.4:
        return 3
    elif fr >= 1:
        if sl > 0.2 or sm > 0 or ss >= 0:
            return 4
        else:
            return 4
    else:
        return 1


class SurveyTemplateView(TemplateView):
    template_name = "survey.html"
    person_model = SurveyedPerson
    geolocation_model = GeolocationPerson
    answer_model = SurveyAnswer

    def post(self, request, *args, **kwargs):
        data = self.request.POST
        # ----------------------
        name = data.get('name')
        identity_number = data.get('identity_number')
        latitude = Decimal(data.get('latitude'))
        longitude = Decimal(data.get('longitude'))
        # ----------------------
        person = self.person_model.objects.get_or_create(name=name, identity_number=identity_number)
        # ----------------------
        q_one = data.getlist('q-1')
        q_two = data.getlist('q-2')
        q_three = data.getlist('q-3')
        q_fourth = data.getlist('q-4')
        q_five = data.getlist('q-5')
        q_six = data.getlist('q-6')
        # ----------------------
        all_responses = q_one + q_two + q_three + q_fourth + q_five + q_six
        # ----------------------
        fr = 0
        # ----------------------
        if 1 in q_two:
            fr += 1
        if 2 in q_two:
            fr += 1
        # ----------------------
        if 1 in q_three:
            fr += 1
        if 2 in q_three:
            fr += 0.6
        # ----------------------
        ss = 0
        if 1 in q_fourth:
            ss += 0.9
        if 2 in q_fourth:
            ss += 0.4
        if 3 in q_fourth:
            ss += 0.8
        # ----------------------
        sm = 0
        if 1 in q_five:
            sm += 0.4
        if 2 in q_five:
            sm += 0.5
        # ----------------------
        sl = 0
        if 1 in q_six:
            sl += 0.15
        if 2 in q_six:
            sl += 0.14
        if 3 in q_six:
            sl += 0.12
        if 4 in q_six:
            sl += 0.06
        if 5 in q_six:
            sl += 0.17
        # ----------------------
        result = valid_result_from_fr(fr, ss, sm, sl)
        survey_number = len(self.geolocation_model.objects.filter(surveyed_person=person[0])) + 1
        geolocation_person = self.geolocation_model.objects.create(surveyed_person=person[0],
                                                                   survey_number=survey_number,
                                                                   latitude=latitude, longitude=longitude,
                                                                   result=result)
        # ----------------------
        for i, rpt in enumerate(all_responses):
            save_responses(self.answer_model, rpt, (i + 1), geolocation_person)
        # print('-------------------')
        # print('Info')
        # print('-------------------')
        # print(name)
        # print(identity_number)
        # print(latitude)
        # print(longitude)
        # print('-------------------')
        # print('Questions')
        # print('-------------------')
        # print(q_one)
        # print(q_two)
        # print(q_three)
        # print(q_fourth)
        # print(q_five)
        # print(q_six)
        # print('-------------------')
        return redirect(reverse('survey_result') + '?identity_number={}'.format(identity_number))


class SurveyResultTemplateView(TemplateView):
    template_name = "survey_result.html"
    person = SurveyedPerson
    geolocation = GeolocationPerson
    answers = SurveyAnswer

    def get_context_data(self, **kwargs):
        context = super(SurveyResultTemplateView, self).get_context_data(**kwargs)
        identity_number = self.request.GET.get('identity_number')
        context['person'] = self.person.objects.get(identity_number=identity_number)
        context['geolocation'] = self.geolocation.objects.filter(surveyed_person=context['person'])
        return context

templates/layout/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://bootswatch.com/4/united/bootstrap.css">
    <style>
        .card-footer {
            border-top: none !important;
        }

        .card-img-top {

        }
    </style>
    <title>{% block title %}COVID-19 | MIT CHALLENGE{% endblock %}</title>
    {% block styles %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">COVID-19 | MIT CHALLENGE | Team A-10</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav"
            aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="main-nav">
        {% include 'layout/links.html' %}
    </div>
</nav>
<br>
<main style="padding: 20px;">
    <div class="card">
        <div class="card-header">
            {% block card-title %}
            {% endblock %}
        </div>
        <div class="card-body">
            {% block card-body %}
            {% endblock %}
        </div>
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/layout/links.html
<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'home_view' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'survey' %}">Covid-19 survey</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Hospitals near to me</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">About covid-19</a>
    </li>
</ul>

templates/survey.html
{% extends 'layout/layout.html' %}

{% block card-title %}
    <h1>Take a quick survey and know if you have symptoms of covid or not</h1>
    <span>( please allow us to get your location to help you as much as we can )</span>
{% endblock %}

{% block card-body %}
    <br>
    <form method="post">
        {% csrf_token %}
        <ul class="list-group">
            <li class="list-group-item">
                <h4>Give us information about you</h4>
                <span>( all of these information will be use just for take care of your health and act as quickly as we can to help you and your family )</span>
                <hr>
                <div class="form-group">
                    <label for="name">Complete Name</label>
                    <input type="text" class="form-control" name="name" id="name">
                </div>
                <div class="form-group">
                    <label for="identity_number">Identity Number</label>
                    <input type="text" class="form-control" name="identity_number" id="identity_number">
                </div>
                <div class="form-group">
                    <input type="text" name="latitude" id="latitude">
                    <small class="form-text text-muted">(this is the latitude of gps, this will be hidden but we will
                        use it
                        to geolocate the persons who submit the survey)</small>
                </div>
                <div class="form-group">
                    <input type="text" name="longitude" id="longitude">
                    <small class="form-text text-muted">(this is the latitude of gps, this will be hidden but we will
                        use it
                        to geolocate the persons who submit the survey)</small>
                </div>
            </li>
            <li class="list-group-item">
                <h4>Tell us about your interaction with other people</h4>
                <label>
                    <input type="checkbox" value="1" name="q-1"> I have been in contact with persons that are at
                    least 2 meters of distance or less
                </label><br>
                <label>
                    <input type="checkbox" value="2" name="q-1"> I had contact with a person that has covid19 for more
                    than 15 minutes
                </label><br>
                <label>
                    <input type="checkbox" value="3" name="q-1"> I had direct contact with the secretion of a probably
                    or
                    confirmed of a covid19 case
                </label><br>
            </li>
            <li class="list-group-item">
                <h4>In the last two weeks ...</h4>
                <label>
                    <input type="checkbox" value="1" name="q-2"> I had a stretch contact with a confirmed case of
                    covid19
                </label><br>
                <label>
                    <input type="checkbox" value="2" name="q-2"> I was or travel to areas that has cases of covid19 and
                    I
                    have symptoms
                </label><br>
                <label>
                    <input type="checkbox" value="3" name="q-2"> None of the above
                </label><br>
            </li>
            <li class="list-group-item">
                <h4>I work in :</h4>
                <label>
                    <input type="checkbox" value="1" name="q-3"> the medical sector or something related to it and I had
                    stretch contact with confirmed cases of covid19
                </label><br>
                <label>
                    <input type="checkbox" value="2" name="q-3"> Any of the following professions: firefighters, police,
                    indigenous guard, taxi driver, transportation, general services or food.
                </label><br>
                <label>
                    <input type="checkbox" value="3" name="q-3"> None of the above
                </label><br>
            </li>
            <li class="list-group-item">
                <h4>Do I have one of the next symptoms?</h4>
                <label>
                    <input type="checkbox" value="1" name="q-4"> Fever greater than or equal to 38 ° C
                </label><br>
                <label>
                    <input type="checkbox" value="2" name="q-4"> Tiredness or fatigue
                </label><br>
                <label>
                    <input type="checkbox" value="3" name="q-4"> Dry cough
                </label><br>
                <label>
                    <input type="checkbox" value="4" name="q-4"> None of the above
                </label><br>
            </li>
            <li class="list-group-item">
                <h4>Do you have any of these symptoms?</h4>
                <label>
                    <input type="checkbox" value="1" name="q-5"> Breathing difficulty
                </label><br>
                <label>
                    <input type="checkbox" value="2" name="q-5"> Sore throat
                </label><br>
                <label>
                    <input type="checkbox" value="3" name="q-5"> None of the above
                </label><br>
            </li>
            <li class="list-group-item">
                <h4>Do you have any of these symptoms?</h4>
                <label>
                    <input type="checkbox" value="1" name="q-6"> Body pain
                </label><br>
                <label>
                    <input type="checkbox" value="2" name="q-6"> Headache
                </label><br>
                <label>
                    <input type="checkbox" value="3" name="q-6"> Nasal congestion
                </label><br>
                <label>
                    <input type="checkbox" value="4" name="q-6"> Mucus (runny nose, runny nose)
                </label><br>
                <label>
                    <input type="checkbox" value="5" name="q-6"> Nausea, vomiting, or diarrhea
                </label><br>
                <label>
                    <input type="checkbox" value="6" name="q-6"> None of the above
                </label><br>
                <br>
                <button type="submit" class="btn btn-primary">Submit</button>
            </li>
        </ul>
    </form>
{% endblock %}

{% block script %}
    <script>
        function getLatitudeLongitude(position) {
            document.getElementById('latitude').value = position.coords.latitude
            document.getElementById('longitude').value = position.coords.longitude
        }

        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(getLatitudeLongitude);
            }
        }

        getLocation()
    </script>
{% endblock %}

templates/survey_result.html
{% extends 'layout/layout.html' %}

{% block card-title %}
    <h1>Your result is :</h1>
{% endblock %}

{% block card-body %}
    <h3>Hi {{ person.name }}</h3>
    <span>This are all the surveys that you have been doing and also the days when you did it</span>
    <br>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Result</th>
            <th scope="col">Day of Survey</th>
        </tr>
        </thead>
        <tbody>
        {% for rpt in geolocation %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td style="color: #FFFFFF;"
                    class="{% if rpt.result == 2 %}bg-info{% elif rpt.result == 3 %}bg-warning{% elif rpt.result == 4 %}bg-danger{% else %}bg-success{% endif %}"
                >{{ rpt.get_result_display }}</td>
                <td>{{ rpt.creation_date }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block script %}
{% endblock %}